### ISSUE TITLE
Proxmox Integrations

### ISSUE THREAD

**Issue by mrprofessork** [Sanjeet990/Astroluma#9]
First off, this is probably the best dashboard I've used. The ease of use, the design, and the customization are terrific, and I can only see it getting better. 

I am having a problem with the proxmox integration though. Proxmox integrations stopped showing up on listings. It was working when I first spun it up but now they have stopped showing on the face of the listing. I tried restarting the container and recreating the integration but had no luck. 

I also recreated the listing with the new integration. Still no luck.

**Comment by Sanjeet990** [comment]
Can you please help with the container logs? This would help me to figure out the issue.

**Comment by mrprofessork** [comment]
I just tested on a larger screen with higher resolution and I can see the Proxmox resource details. That was the issue. The resource usage details were not showing up on my 13 inch macbook browser but is showing on my 24 inch monitor.  It may be a matter of how responsive the design is. I will close this issue.

**Comment by Sanjeet990** [comment]
I see. When on smaller displays, it hides the app integration details due to responsiveness. If so, you can still see the details by clicking this icon.

![image](https://github.com/user-attachments/assets/5824432d-e3dd-4170-ab1a-69685fe22342)

This brings back the app integration view like this:

![image](https://github.com/user-attachments/assets/7f3887ec-046e-437b-a925-efe1a2c99e85)

**Comment by mrprofessork** [comment]
yes I did see that, thanks again.
